[package]
name = "smithay-client-toolkit"
version = "0.15.3"
authors = ["Victor Berger <victor.berger@m4x.org>"]
documentation = "https://smithay.github.io/client-toolkit"
repository = "https://github.com/smithay/client-toolkit"
license = "MIT"
edition = "2018"
categories = ["gui"]
keywords = ["wayland", "client"]
description = "Toolkit for making client wayland applications."
readme = "README.md"

[package.metadata.docs.rs]
features = ["calloop", "xkbcommon"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitflags = "1.0"
nix = "0.23"
dlib = "0.5"
lazy_static = "1.0"
memmap2 = "0.5"
log = "0.4"
thiserror = "1.0.30"
wayland-backend = "=0.1.0-alpha10"
wayland-client = "=0.30.0-alpha10"
wayland-protocols = { version = "=0.30.0-alpha10", features = ["client", "unstable_protocols"] }
wayland-cursor = "=0.30.0-alpha10"
# Explicit dependency until release
xkbcommon = { version = "=0.5.0-beta.0", optional = true, features = ["wayland"] }
calloop = { version = "0.9", optional = true }

[features]
default = ["calloop", "xkbcommon"]
Clickable = []
Keyboard = []
Scrollable = []
Window = []
Layer = []
Motion = []

[build-dependencies]
pkg-config = "0.3"

[dev-dependencies]
image = "0.23"
env_logger = "0.9"

rusttype = "0.9"
tempfile = "3.2"
once_cell = "1.7"
async-trait = "0.1.30"
failure = "0.1.8"
reqwest = { version = "0.10.4", features = ["json"] }
quick-js = "0.3.0"
urlencoding = "1.0.0"
futures = "0.3.4"
tokio = { version = "0.2", features = ["macros"] }
serde_json = "1.0"

[dev-dependencies.lib-poki-launcher]
version = "0.5.0"
path = "../lib-poki-launcher"

[dev-dependencies.rusty_pipe]
version = "0"
path = "../rusty_pipe-master"
